#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure databases/mysql-server databases/mysql55-server
  pkg ensure databases/percona-toolkit
}

bootstrap
